name: feira_mensal_app
description: Aplicativo Flutter para controle de compras de mercado e feira mensal.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Gerenciamento de estado
  flutter_riverpod: ^2.6.1

  # Navegação
  go_router: ^16.0.0

  # Banco local (offline first)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Datas e moeda
  intl: ^0.20.2

  # IDs únicos
  uuid: ^4.5.1

  # Gráficos
  fl_chart: ^1.0.0

  # Preferências locais
  shared_preferences: ^2.5.3
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
