// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCD0erBFJPmpInqNbzcRfrAayTsOEzho',
    appId: '1:817589523022:web:288b83be09bd66fa34291f',
    messagingSenderId: '817589523022',
    projectId: 'feira-mensal-app',
    authDomain: 'feira-mensal-app.firebaseapp.com',
    storageBucket: 'feira-mensal-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAbUrEWCnhS0mDllEEcWA1ALqIZoUbmI',
    appId: '1:817589523022:android:383df14d9d5fafea34291f',
    messagingSenderId: '817589523022',
    projectId: 'feira-mensal-app',
    storageBucket: 'feira-mensal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIUMsZDYgWGfD_YRyHpMqqYuMXZD6dn4',
    appId: '1:817589523022:ios:9e7446d48e79264b34291f',
    messagingSenderId: '817589523022',
    projectId: 'feira-mensal-app',
    storageBucket: 'feira-mensal-app.firebasestorage.app',
    iosBundleId: 'com.example.feiraMensalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsIUMsZDYgWGfD_YRyHpMqqYuMXZD6dn4',
    appId: '1:817589523022:ios:9e7446d48e79264b34291f',
    messagingSenderId: '817589523022',
    projectId: 'feira-mensal-app',
    storageBucket: 'feira-mensal-app.firebasestorage.app',
    iosBundleId: 'com.example.feiraMensalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLCD0erBFJPmpInqNbzcRfrAayTsOEzho',
    appId: '1:817589523022:web:7f2e6ec92124389734291f',
    messagingSenderId: '817589523022',
    projectId: 'feira-mensal-app',
    authDomain: 'feira-mensal-app.firebaseapp.com',
    storageBucket: 'feira-mensal-app.firebasestorage.app',
  );
}
